ndarray n维数组是numpy的核心特点
每个ndarray中的元素都应该是相同类型的
每个ndarray都有shape和dtype两个属性

In [ ]:
import numpy as np

data=np.array([[1,2,3],[4,5,6]])
print(data)
#ndarray支持所有标量运算
print(data+data)

In [ ]:
print(data.shape)
print(data.dtype)

创建ndarray可以使用array函数
zeros/ones函数创建全01数组传入元组确定形状
empty生成一个空值ndarray

In [ ]:
lis=[x for x in range(10) if x%2==0]
arr1=np.array(lis)
print(arr1)
arr2=np.zeros((3,4))
arr3=np.ones((4,3))
print(arr2,arr3,sep="\n")

np.arange是内置函数range的数组版
多维要使用.reshape

In [ ]:
print(np.arange(1,15,3))

创建ndarray时可以指定dtype（直接使用数据类型或者np.数据类型都可以）
使用astype函数转换数据类型（不建议对string类型使用强转）

In [ ]:
arr_float=np.array([1.7,2.1,0.8,0.6],dtype=np.float64)
print(arr_float.dtype)
arr_int=arr_float.astype(np.int32)
print(arr_int.dtype)
print(arr_int)

numpy数组的运算称为向量化
大小相等的数组的任何运算都会作用到元素
进行大小比较则会产生bool数组

In [ ]:
arr0=np.array([[1.7,2.0,2.1,0.8],[1.0,0.6,1.1,2.1]])
print(arr0*2,arr0+20,1/arr0,arr0**2,sep="\n\n")
arr=np.arange(0,2,0.25).reshape(2,4)
print("\n",arr>=arr0)

list列表存放的内容本质是元素的内存地址指针
切片读取会创建全新列表（浅拷贝）切片赋值会直接修改原列表

In [ ]:
lis0=list(range(10))
print(lis0,id(lis0),sep="\t")
lis1=lis0[4:8]
print(lis1,id(lis),sep="\t")
lis0[4:8]=[30,20,40]
print(lis0,id(lis0),sep="\t")

#切片赋值替换元素的个数不一定要和切片长度相等
lis0[5:6]=[x for x in range(10) if x%2!=0]
print(lis0,id(lis0),sep="\t")
#在某个指定位置插入列表不覆盖原内容
#或者直接删除列表内容
lis0[5:5]=[10,20,30,40]
print(lis0,id(lis0),sep="\t")
lis0[:]=[]
print(lis0)

数组切片是原始数组的视图
任何修改会直接作用到原数组上

In [ ]:
arr=np.arange(10)
print(arr)
#先创建一个原始数组的切片
arr_lis=arr[4:7]
print(arr_lis)
#对切片进行赋值
arr_lis[:]=20
print(arr)#会修改原数组


lis_arr=[x for x in range(10)]
print(lis_arr)
lis_arr_1=lis_arr[4:8]
print(lis_arr_1)
lis_arr_1[:]=[20,20,20,20]#这里有一个细微的差别
print(lis_arr,lis_arr_1,sep="\n")#证明list和array的区别

对于高维数组单独索引返回低维度数组
标量值和数组都可以赋值给切片

In [ ]:
arr2d=np.array([[1,2,3,4],[3,4,5,6]],dtype=np.int32)
print(arr2d,arr2d[0],arr2d[0,1],sep="\n\n")
arr3d=np.arange(12).reshape(2,2,3)
#三维的数组(Z,X,Y)
print(arr3d,arr3d[0],arr3d[0,1],arr3d[0,1,2],sep="\n\n")
#使用copy方法创建一个副本
val_copy=arr3d[0].copy()
arr3d[0]=30
print(arr3d)

高维数组的切片索引shape会返回选中区域
混合索引和整数索引shape会降维
只返回该行列向量所包含的元素个数

In [ ]:
arr_2d=np.arange(12).reshape(4,3)
print(arr_2d)
print(arr_2d[:3,:2],arr_2d[:3,:2].shape,sep="\t\t")
print(arr_2d[1:3,1:3],arr_2d[1:3,1:3].shape,sep="\t\t")
print(arr_2d[3],arr_2d[3].shape,sep="\t\t")
print(arr_2d[0,:2],arr_2d[0,:2].shape,sep="\t\t")

布尔型索引：bool数组（不能使用and和or只能使用&和|）
通过bool数组设置值是通过等号右侧的值替换True值

In [ ]:
names_lis=np.array(["xiaoming","xiaobai","xiaohan","xiaobai","xiaoming","xiaohan"])
score_lis=np.array([[1,2],[3,7],[6,3],[9,8],[7,5],[0,4]])
print(names_lis=="xiaoming")
print(score_lis[names_lis=="xiaoming"],"\n")#只对0轴（行）进行操作
print(score_lis[names_lis=="xiaoming",1],"\n")#先对行后对列，降维返回一维数组
print(score_lis[names_lis=="xiaoming",1:],"\n")#先对行后对列，不降维返回列向量
print(score_lis[names_lis=="xiaoming"][1],"\n")#分布链式索引
score_lis[names_lis!="xiaobai"]=99
print(score_lis)

一维数组的花式索引

In [ ]:
arr_1=np.array([1,2,3,4,5])
index_num=[0,2,4]
print(arr_1,arr_1[index_num],sep="\n\n")

高维数组的花式索引分为坐标模式和提取子矩阵模式
提取子矩阵推荐使用ix函数

In [ ]:
arr_2=np.arange(20).reshape(5,4)
rows=[2,4]
cols=[1,3]
print(arr_2)
print(arr_2[rows,cols])
print(arr_2[np.ix_(rows,cols)])

花式索引会产生副本而切片只是试图

In [43]:
arr = np.array([10, 20, 30])
arr_arr=arr.copy()
# 基础切片 -> 视图
slice_arr = arr[0:2]
slice_arr[0] = 999
print(arr[0])  # 输出 999（原数组被改变了）

# 花式索引 -> 副本
fancy_arr = arr_arr[[0, 1]]
fancy_arr[0] = -1
print(arr_arr[0])  # 输出 10（原数组未受影响）

999
10


转置和矩阵乘法

In [47]:
arr_t=np.arange(12).reshape(4,3)
print(arr_t,arr_t.T,sep="\n\n")
print(np.dot(arr_t,arr_t.T))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
