生成伪随机数

In [ ]:
import numpy as np

data=np.random.standard_normal(size=(2,3))
print(data)
rng=np.random.default_rng(seed=12345)
data=rng.standard_normal(size=(2,3))
print(data)

通用函数：简单函数的快速向量化封装

In [ ]:
arr=np.arange(10)
print(arr)
arr=np.sqrt(arr)
print(arr)

arr1=np.random.standard_normal(size=(3,4))
arr2=np.random.standard_normal(size=(3,4))
print(np.maximum(arr1,arr2))

面向数组编程：用数组表达式替代显式的循环语法（向量化）
1. 通用函数和三元表达式
2. 广播机制Broadcast
3. 布尔掩码和聚合统计
4. 花式索引和轴向变形

广播机制：对形状不同的数组进行变形并计算
从后往前比较数组形状当且仅当维度大小相等或者其中一个维度为1才兼容
形状较小的数组会在维度为1的轴上进行复制扩展

In [ ]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d+10,"\n\n")#标量10被广播为[10,10,10,10,10]

A=np.ones((4,4))
B=np.array([1,2,3,4])
print(A,A.shape,B,B.shape,sep="\n\n")
#可以理解为B自动广播为四行[1,2,3,4]
print("\n",A+B)

通用函数是对数组元素执行元素级运算的函数（向量化包装器）
分为一元ufunc和二元ufunc（分别接收一个和两个数组并返回一个数组）
三元表达式np.where

In [ ]:
#np.where是Python中x if condition else y的向量化版本
#np.where(condition,x,y)
arr_=np.random.standard_normal(size=(2,3))
print(arr_)
result_=np.where(arr_<0,0,arr_)
print(result_)

布尔掩码：通过条件判断生成一个布尔数组（True/False）然后用这个布尔数组来过滤或索引原数组
组合bool条件不能使用and/or关键词必须使用位运算符
聚合统计可以按轴对数组进行降维计算

In [ ]:
C=np.arange(15).reshape(3,5)
D=np.random.standard_normal(size=(3,5))
#转置点积生成5×5的矩阵
request_=np.dot(C.T,D)>0
print(request_)
E=np.array([1,2,3,4,5])
#需要一个高维数组的单独索引返回低维向量
#用这个向量提供的bool掩码过滤数据
print(E[request_[0]])

print(C.sum())
#按列求和就是横向压缩
print(C.sum(axis=1))
print(C.sum(axis=1).shape)

In [26]:
#使用arr.sort()方法原地修改
arr_A=np.random.standard_normal(size=(2,4))
print(arr_A,"\n")
arr_A.sort(axis=-1)
print(arr_A)
print("\n\n")
#使用arr_sort=np.sort(arr)会返回新数组原数组不改变
arr_sort=np.sort(arr_A,axis=-1)
print(arr_sort)

[[-1.73616834 -0.05003856 -1.55657132  1.09110871]
 [ 0.70055507 -0.59391193 -0.44649121 -0.7962577 ]] 

[[-1.73616834 -1.55657132 -0.05003856  1.09110871]
 [-0.7962577  -0.59391193 -0.44649121  0.70055507]]



[[-1.73616834 -1.55657132 -0.05003856  1.09110871]
 [-0.7962577  -0.59391193 -0.44649121  0.70055507]]
